__all__ = ['SCREEN_WIDTH', 'SCREEN_HEIGHT', 'GRID_SIZE', 'GRID_WIDTH',
           'GRID_HEIGHT', 'UP', 'DOWN', 'LEFT', 'RIGHT',
           'BOARD_BACKGROUND_COLOR', 'BORDER_COLOR', 'APPLE_COLOR',
           'SNAKE_COLOR', 'ENEMY_SNAKE_COLOR', 'ROCK_COLOR',
           'SPEED', 'TITLE']

# Window constants:
SCREEN_WIDTH, SCREEN_HEIGHT = 640, 480
GRID_SIZE = 20
GRID_WIDTH = SCREEN_WIDTH // GRID_SIZE
GRID_HEIGHT = SCREEN_HEIGHT // GRID_SIZE

# Directions:
UP = (0, -1)
DOWN = (0, 1)
LEFT = (-1, 0)
RIGHT = (1, 0)

# Colors:
BOARD_BACKGROUND_COLOR = (0, 0, 0)
BORDER_COLOR = (93, 216, 228)
APPLE_COLOR = (255, 0, 0)
SNAKE_COLOR = (0, 255, 0)
ENEMY_SNAKE_COLOR = (1, 1, 1)
ROCK_COLOR = (211, 211, 211)

# Game parametrs
SPEED = 7

# Names:
TITLE = 'Удав'
